server:
  port: 8300

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lvchaogit/SpringCloud
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/ # 服务注册中心地址